baseURL: https://dhruvmg-thoughts.netlify.app/
languageCode: en-us
title: Portfolio Website for Dhruv Ghurburrun
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
     #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hello. My name is Dhruv. Welcome to my website. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Balcombe Street
        title: 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: dghurburrun.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- #icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/DhruvM.G
      #- #icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/dhruvMg1804
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/dhruv-ghurburrun-aa021a140/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: meeee
  tiles:
    enable: yes
    showcase:
      - image: Mauritius.jpg
        subtitle: Home
        title: Mauritius
        url: blogs/risk_return1
      - image: pic02.jpg
        subtitle: Pursuit of happiness
        title: My journey
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: Inspiration
        title: Books
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Pleasure 
        title: Movies
        url: blogs/Story
      - image: Food.jpg
        subtitle: Life
        title: Food
        url: blogs/ipsum
      - image: London.jpeg
        subtitle: The City
        title: London
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Being passionate by investments and more specifically, stocks, I have built a small portfolio of stocks with my savings. 
    Having lived in Mauritius for the past 2 years, I have invested in stocks listed in the stock exchange of Mauritius. 
      "
    title: Passion
    url: blogs

